print("Step 1")
source('./code/ReadandClean.R')
rm(list = ls())
print("Step 2")
source('./code/dataSample.R')
rm(list = ls())
print("Step 3")
source('./code/ngramcreate.R')
rm(list = ls())
print("Paso 4")
source('./code/ngramread.R')
print("Step 5 - Prediction")
source('./code/Predictiontext.R')